#该文件仅用于开发时或本地自行验证，与正式业务并不一致，本地配置与远程配置不能同时使用
apiConfig:
  api:
    "[/decrypt]": http://172.16.40.228:19081/ability/atom/cipher/gateway-key-decrypt
orgConfig:
  org1:
    state: 0
    publicKey: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEp1eXv2rWsP2m3euAc4bQK4TVebwvvHmWbRSGWGXFvCb0wZr4ynTHVRWM8WAzAGcZvo6UB5s9W4FXtaXdKlzTyw==
    privateKey: MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgg4QF9k3LEUWOsdO+t+FLXYY7yzdNwOxYTSvKTFGx5s2gCgYIKoEcz1UBgi2hRANCAASnV5e/ataw/abd64BzhtArhNV5vC+8eZZtFIZYZcW8JvTBmvjKdMdVFYzxYDMAZxm+jpQHmz1bgVe1pd0qXNPL
    flowLimit:
      '[/decrypt]':
        day: 10000000
        second: 10000
    appConfig:
      app1:
        state: 0
        authorities:
          - "/decrypt"